DROP DATABASE IF EXISTS MOVIES;
CREATE DATABASE MOVIES CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI ;                         OR (CREATE DATABASE MOVIES;)(CREATE DATABASE IF NOT EXISTS MOVIES;)
SHOW DATABASES;
USE MOVIES;
 
CREATE TABLE MOVIE( 
 MOVIE_ID TINYINT NOT NULL UNIQUE ,
 MOVIE_TITLE VARCHAR(50) NOT NULL,
 MOVIE_DESC VARCHAR(120),
 MOVIE_IMG_PATH VARCHAR(40),   
 TRAILER_PATH VARCHAR(70),            
 YEAROFRELEASE YEAR, 
 LIKES INTEGER, 
  PRIMARY KEY (MOVIE_ID))ENGINE=INNODB;
  
(OR MOVIE_IMG LONGBLOB DEFAULT NULL, #PICTURE IN DATABASE AS BLOB)
(OR TRAILER LONGBLOB)


CREATE TABLE GENRE(
GENRE_ID TINYINT NOT NULL UNIQUE,
GENRE_TYPE VARCHAR(15) NOT NULL,
PRIMARY KEY(GENRE_ID))ENGINE=INNODB;

CREATE TABLE MOVIE_GENRE(
MOVIE_ID TINYINT NOT NULL UNIQUE,
GENRE_ID TINYINT NOT NULL UNIQUE,
FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(MOVIE_ID)
ON DELETE CASCADE 
ON UPDATE CASCADE,
FOREIGN KEY (GENRE_ID) REFERENCES GENRE(GENRE_ID)
ON DELETE CASCADE 
ON UPDATE CASCADE,
PRIMARY KEY (MOVIE_ID, GENRE_ID))ENGINE=INNODB;

CREATE TABLE ACTOR(
ACTOR_ID TINYINT NOT NULL UNIQUE,
FIRSTNAME VARCHAR(25),
SURNAME VARCHAR(35),
PRIMARY KEY(ACTOR_ID))ENGINE=INNODB;

CREATE TABLE MOVIE_ACTOR(
ACTOR_ID TINYINT NOT NULL,
MOVIE_ID TINYINT NOT NULL ,
FOREIGN KEY (ACTOR_ID) REFERENCES ACTOR(ACTOR_ID)
ON DELETE CASCADE 
ON UPDATE CASCADE,
FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(MOVIE_ID)
ON DELETE CASCADE 
ON UPDATE CASCADE,
PRIMARY KEY (ACTOR_ID, MOVIE_ID))ENGINE=INNODB;

CREATE TABLE DIRECTOR(
DIRECTOR_ID TINYINT NOT NULL UNIQUE,
DIRFNAME VARCHAR(25) NOT NULL,
DIRSNAME VARCHAR(35) NOT NULL,
MOVIE_ID TINYINT,
FOREIGN KEY(DIRECTOR_ID) REFERENCES MOVIE(MOVIE_ID)
ON DELETE CASCADE ON UPDATE CASCADE,
PRIMARY KEY(DIRECTOR_ID))ENGINE=INNODB;

 
 
INSERT INTO MOVIE VALUES (001, "LEGO MOVIE 2", "LEGO DUPLO INVADERS FROM OUTER SPACE, WRECKING EVERYTHING FASTER THAN THEY CAN REBUILD.", LOAD_FILE("C:\USERS\GARDI\DESKTOP\LM2"), LOAD_FILE("C:\USERS\GARDI\DESKTOP\LEGO-MOVIE.MOV"),2019,1);
INSERT INTO GENRE VALUES(100, "ANIMATION");
INSERT INTO MOVIE_GENRE VALUES(001,100); 
